config/routes.rb
Rails.application.routes.draw do
  resources :properties
      root 'pages#home'

  # Devise
  devise_for :users,  controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: 'registrate' }

  # Vistas estaticas
  get '/home',    to: 'pages#home'
  get '/privacy', to: 'pages#privacy'
  get '/legal',   to: 'pages#terms'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :operation
  has_many :propertyoperations, dependent: :destroy
  has_many :products, through: :propertyoperations
  has_one_attached :photo  

  validates :operation,       presence: true,
                              uniqueness: true
  validates :address,         presence: true,
                              length: { minimum: 10 }
  validates :price,           presence: true,
                              numericality: { greater_than: 0 }
  validates :release_date,    presence: true
  validates :link_to_website, presence: true,
                              format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/ },
                              uniqueness: true

end

app/controllers/concerns/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  # GET /properties or /properties.json
  def index
            @pagy, @properties = pagy(Property.all)
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
      def new
            @property = current_user.properties.build
          end
      end


  # GET /properties/1/edit
  def edit
      if current_user.id == @property.user_id
        @property = Property.find(params[:id])
      else
        redirect_to root_path, notice: 'No puedes editar una propiedad que no es tuya'
      end
  end

  # POST /properties or /properties.json
  def create
    @property = current_user.properties.build(property_params)
    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:photo, :operation_id, :precio, :type_money, :m2, :address, :release_date, :link_to_website, :available, { feature_ids: [] })
    end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
      def new
            @property = current_user.properties.build
          end
      end

  # GET /properties/1/edit
  def edit
      if current_user.id == @property.user_id
        @property = Property.find(params[:id])
      else
        redirect_to root_path, notice: 'No puedes editar una propiedad que no es tuya'
      end
  end

  # POST /properties or /properties.json
  def create
    @property = current_user.properties.build(property_params)
    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:operation_id, :precio, :type_money, :m2, :address, :release_date, :link_to_website, :available, { feature_ids: [] })
    end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :operation_id, style: "display: block" %>
    <%= form.text_field :operation_id %>
  </div>

  <div>
    <%= form.label :operation_id, style: "display: block" %>
    <%= form.collection_select :operation_id,
        Operation.where(available: true), :id, :name,
        include_blank: true,
        required: true
    %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo, accept: "image/*" %>
  </div>
      
  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio 
    min: 0
    %>
  </div>

  <div>
    <%= form.label :type_money, style: "display: block" %>
    <%= form.text_field :type_money 
    required: true,
    %>
  </div>

  <div>
    <%= form.label :m2, style: "display: block" %>
    <%= form.text_field :m2 
    required: true
    %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address 
    required: true,
    %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date 
    required: true,
    value: Date.today
    %>
  </div>

  <div>
    <%= form.label :link_to_website, style: "display: block" %>
    <%= form.text_field :link_to_website
    required: true, 
    value: "https://"
    %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>
  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>User:</strong>
    <%= property.user.full_name %>
  </p>

  <p>
    <strong>Operation:</strong>
    <%= property.operation_id %>
  </p>
  
  <p>
    <strong>Photo:</strong>
    <% if property.photo.attached? %>
      <%= image_tag property.photo %>
    <% else %>
      <img src="https://picsum.photos/200/300" alt="">
    <% end %>
  </p>

  <p>
    <strong>Operations:</strong>
    <% property.operations.each do |operation| %>
      <%= operation.type %>
    <% end %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= property.precio %>
  </p>

  <p>
    <strong>Type money:</strong>
    <%= property.type_money %>
  </p>

  <p>
    <strong>M2:</strong>
    <%= property.m2 %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= property.release_date %>
  </p>

  <p>
    <strong>Link to website:</strong>
    <%= property.link_to_website %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= property.available %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Properties</h1>

<div id="properties">
  <% @properties.each do |property| %>
    <%= render property %>
    <p>
      <%= link_to "Show this property", property %>
    </p>
  <% end %>
</div>
<%# Paginación %>
<% link = pagy_link_proc(@pagy, link_extra: 'class="page-link"') %>
<%#                            -%><nav class="pagy-bootstrap-nav" role="navigation">
<%#                            -%>  <ul class="pagination">
<% if @pagy.prev                -%>    <li class="page-item prev"><%== link.call(@pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% @pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if @pagy.next                -%>    <li class="page-item next"><%== link.call(@pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
 </ul>
</nav>
<%= link_to "New property", new_property_path %>
<%= raw pagy_nav(@pagy) %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <% if user_signed_in? %>
    <% if current_user.id == @property.user_id %>
      <%= link_to "Edit this property", edit_property_path(@property) %> |
      <%= link_to "Back to property", properties_path %>
    <% end %>
  <% end %>
  <%= button_to "Destroy this property", @property, method: :delete %>
</div>